version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    working_dir: /var/www/html
    command: >
      sh -c "php artisan migrate --force && php-fpm"
    networks:
      - laravel

  nginx:
    image: nginx:latest
    container_name: laravel_nginx
    restart: unless-stopped
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    networks:
      - laravel
    depends_on:
      - app

  # mysql:
  #   image: mysql:8.0
  #   container_name: laravel_mysql
  #   restart: unless-stopped
  #   environment:
  #     MYSQL_ROOT_PASSWORD: root_password
  #     MYSQL_DATABASE: laravel
  #     MYSQL_USER: laravel_user
  #     MYSQL_PASSWORD: laravel_password
  #   networks:
  #     - laravel
  #   ports:
  #     - "3306:3306"
    postgres:
    image: postgres:13
    container_name: laravel_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: laravel
      POSTGRES_USER: laravel_user
      POSTGRES_PASSWORD: laravel_password
    networks:
      - laravel
    ports:
      - "5432:5432"

networks:
  laravel:
